# url: https://SidMasih.github.io
# baseurl: /churchwebsite/
url: http://journeychristianfellowship.herokuapp.com
plugins: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Site settings
title: Journey Christian Fellowship
email: fiabraham@journeychristianfellowship.community
description: "Journey Christian Fellowship is a Bible believing, Spirit-filled, welcoming church located in Walnut Creek, CA. Our goal is to lead people into a growing relationship with God no matter where they at their journey in life."


# Team names, titles and social links
people:
- name: Finny Abraham
  pic: 3
  position: Pastor
  summary: Finny Abraham was born in UAE (Dubai), brought up in India and is currently studying in the USA. Growing up in a pastoral family, Finny acquired a great passion to serve people and bring them into a closer relationship with God. After completing his Masters in Social Work, Finny came to the United States to study for his Masters in Divinity at Fuller Theological Seminary. While there, he began his ministry as a pastor of an English ministry at a Korean-American church. Presently, he is a PhD student focusing on New Testament studies at the Graduate Theological Union in Berkeley, CA. Finny enjoys preaching the Word in a systematic manner, inspiring people to love reading the Scripture, and challenging them to live by its values. Having lived in 3 different countries, Finny integrates well with all cultures for the purpose of sharing the gospel.
  social:
    - title: email
      url: MAILTO:abraham.finny@gmail.com

- name: Monica Chenglo
  pic: 3
  position: Programs Coordinator
  social:
    - title: email
      url: MAILTO:mochenglo@journeychristianfellowship.community

- name: Steve George
  pic: 3
  position: Worship Leader
  social:
    - title: email
      url: MAILTO:stgeorge@journeychristianfellowship.community


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/JourneyChristianEnglishFellowship/?fref=ts
  - title: youtube
    url: https://www.youtube.com/channel/UC0JBMSs9Kfh3v05lv88r5Eg
  - title: yelp
    url: https://www.yelp.com/biz/formosan-umc-of-the-east-bay-walnut-creek

# Postal address (add as many lines as necessary)
address:
  - line: 1755 Sunnyvale Ave.
  - line: Walnut Creek, CA 94597

# Build settings
markdown: kramdown
permalink: pretty
