# url: https://SidMasih.github.io
# baseurl: /churchwebsite/
url: http://journeychristianfellowship.herokuapp.com
plugins: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Site settings
title: Journey Christian Fellowship
email: fiabraham@journeychristianfellowship.community
description: "Journey Christian Fellowship is a Bible believing, Spirit-filled, welcoming church located in Walnut Creek, CA. Our goal is to lead people into a growing relationship with God no matter where they at their journey in life."


# Team names, titles and social links
people:
- name: Finny Abraham
  pic: Finny_Abraham
  position: Pastor
  summary: Finny Abraham was born in UAE (Dubai), brought up in India and is currently studying in the USA. Growing up in a pastoral family, Finny acquired a great passion to serve people and bring them into a closer relationship with God. After completing his Masters in Social Work, Finny came to the United States to study for his Masters in Divinity at Fuller Theological Seminary. While there, he began his ministry as a pastor of an English ministry at a Korean-American church. Presently, he is a PhD student focusing on New Testament studies at the Graduate Theological Union in Berkeley, CA. Finny enjoys preaching the Word in a systematic manner, inspiring people to love reading the Scripture, and challenging them to live by its values. Having lived in 3 different countries, Finny integrates well with all cultures for the purpose of sharing the gospel.
  social:
    - title: email
      url: MAILTO:abraham.finny@gmail.com

- name: Monica Chenglo
  pic: Monica_Chenglo
  position: Programs Coordinator
  summary: Monica Chenglo is currently a graduate student pursuing a Masters in Speech Language Pathology. Prior, she received her bachelors in Molecular, Cell, and Developmental Biology. Initially, she intended on becoming a science teacher; however, felt that the essence of education is rooted in expression and communication. By junior year, she decided to reconsider her career endeavors and fell in love with Speech Pathology due to its unique and cohesive nature of serving and assisting, while applying both artistic and scientific methods. Having grown up at East Bay Formosan United Methodist Church, Monica divides her time both in the East Bay and South Bay. She enjoys working alongside the team, bouncing off ideas, and creating new programs for Journey Christian Fellowship. Most importantly, she hopes to provide a space for the community, to collaborate, grow, and feel welcomed.
  social:
    - title: email
      url: MAILTO:monica.chenglo@gmail.com

- name: Stephanas "Steve" George
  pic: Steve_George
  position: Worship Leader
  social:
    - title: email
      url: MAILTO:stephanas.george@gmail.com


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/JourneyChristianEnglishFellowship/?fref=ts
  - title: youtube
    url: https://www.youtube.com/channel/UC_Whwnylj0PCASNNh7ae3GA/videos
  - title: yelp
    url: https://www.yelp.com/biz/formosan-umc-of-the-east-bay-walnut-creek
  - title: instagram
    url: https://www.instagram.com/jcf.walnutcreek/
  - title: soundcloud
    url: https://soundcloud.com/jcfmedia

# Postal address (add as many lines as necessary)
address:
  - line: 1755 Sunnyvale Ave.
  - line: Walnut Creek, CA 94597

# Build settings
markdown: kramdown
permalink: pretty
